version: '3'
services:
  web-app:
    build: web-app
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-app/src:/web-application/src"
    depends_on: 
      - "db"
  db:
    build: db
    ports: 
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=abc123"
      - "MYSQL_DATABASE=myDB"
  redis: 
    image: "redis"
    container_name: "cache"
    ports: 
      - "6379:6379"
  postgreDB:
    image: "postgres"
    container_name: "postgreDB"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=db"
      - "POSTGRES_USER=abc321"
      - "POSTGRES_PASSWORD=myPostgresDB"