version: '3'
services:
  rest-api:
    build: web-app/src/plRestApi
    ports:
      - "3000:3000"
      - "9230:9230"
    volumes:
      - "./web-app/src:/rest-api/src"
    depends_on: 
      - "db"
  spa:
    build: web-app/src/spa/frontend
    ports:
      - "4000:4000"
    volumes:
      - "./web-app/src:/spa/src"
  web-app:
    build: web-app
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-app/src:/web-application/src"
    depends_on: 
      - "db"
  db:
    build: db
    ports: 
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=abc123"
      - "MYSQL_DATABASE=myDB"
  redis: 
    image: "redis"
    container_name: "cache"
    ports: 
      - "6379:6379"