version: '3'
services: 
    web-app:
        build: web-application
        ports: 
            - "8080:8080"
        volumes: 
            - "./web-application/src:/web-application/src"
        depends_on: 
            - "db"
    db:
        build: db
        ports: 
            - "3306:3306"
        environment: 
            - "MYSQL_ROOT_PASSWORD=abc123"
            - "MYSQL_DATABASE=myDB"
